// Animals: the original preguntario bestiary. Each badge is 16×16 pixel art as text,
// drawn as the left half and mirrored. '.' is transparent; other characters are palette keys.
import { mirror } from '../render.mjs';

export default {
  name: 'Animals',
  badges: {
    owl: {
      hint: 'Asks WHY something works; wants the underlying concept',
      text: {
        es: { name: 'Búho', kind: 'Pregunta el porqué' },
        en: { name: 'Owl', kind: 'Asks why' },
      },
      crownY: 0,
      palette: { k: '#2b1d14', b: '#8a5a3b', d: '#5e3b25', l: '#e8cfa8', w: '#ffffff', y: '#f2b33d', o: '#e07b2a' },
      shiny: { b: '#5b6b8c', d: '#3b4660', l: '#d9e2f2' },
      rows: mirror([
        '........',
        '..k.....',
        '..kk....',
        '..kbkkkk',
        '..kbbbbb',
        '.kbwwwwb',
        '.kbwkkwb',
        '.kbwkkwb',
        '.kbwwwwb',
        '.kbbbbby',
        '.kdbllll',
        '.kdbllll',
        '.kdbllll',
        '..kdbbll',
        '...kkkkk',
        '....o.o.',
      ]),
    },
    beaver: {
      hint: 'Asks HOW to do something concrete, step by step',
      text: {
        es: { name: 'Castor', kind: 'Pregunta el cómo' },
        en: { name: 'Beaver', kind: 'Asks how' },
      },
      crownY: 1,
      palette: { k: '#2a1a10', b: '#9b6237', t: '#e3c49a', w: '#ffffff', p: '#d98b7a' },
      shiny: { b: '#c9a14a', t: '#fff1c9' },
      rows: mirror([
        '........',
        '........',
        '..kk....',
        '.kbpk...',
        '.kbbkkkk',
        '.kbbbbbb',
        'kbbbbbbb',
        'kbbbkbbb',
        'kbbbbbbb',
        'kbbbbttt',
        'kbbbtttk',
        '.kbbtttt',
        '.kbbbttw',
        '..kbbbkw',
        '...kkkkk',
        '........',
      ]),
    },
    fox: {
      hint: 'Skeptical: challenges a claim, asks about limits, risks or errors',
      text: {
        es: { name: 'Zorro', kind: 'Pregunta escéptica' },
        en: { name: 'Fox', kind: 'Skeptical question' },
      },
      crownY: 2,
      palette: { k: '#24160f', o: '#e8742c', w: '#fbf3e6', p: '#f4b09a' },
      shiny: { o: '#c9cdd6', p: '#9fb6e0' },
      rows: mirror([
        '........',
        '.k......',
        '.kk.....',
        '.kpk....',
        '.kppk...',
        '.kopokkk',
        '.koooooo',
        'kooooooo',
        'kookoooo',
        'kwwooooo',
        '.kwwwooo',
        '..kwwwww',
        '...kwwww',
        '....kwwk',
        '.....kkk',
        '........',
      ]),
    },
    octopus: {
      hint: 'Connects the topic to their own job, company or a real case',
      text: {
        es: { name: 'Pulpo', kind: 'Lo conecta con su trabajo' },
        en: { name: 'Octopus', kind: 'Connects it to their work' },
      },
      crownY: 0,
      palette: { k: '#2a1430', m: '#b04fc4', l: '#e19af0', w: '#ffffff' },
      shiny: { m: '#3fa58f', l: '#9be8d4' },
      rows: mirror([
        '........',
        '....kkkk',
        '...kmmmm',
        '..kmmmmm',
        '..kmlmmm',
        '.kmmmmml',
        '.kmwwmmm',
        '.kmwkmmm',
        '.kmmmmmm',
        '..kmmmmk',
        '.kmmmmmm',
        'kmmkmmkm',
        'kmkkmkkm',
        'km.km.km',
        '.k..k..k',
        '........',
      ]),
    },
    cat: {
      hint: 'Curious tangent: related, but off the main path',
      text: {
        es: { name: 'Gato', kind: 'Curiosidad lateral' },
        en: { name: 'Cat', kind: 'Curious tangent' },
      },
      crownY: 2,
      palette: { k: '#1f1f26', g: '#8c8f99', p: '#f2a1b0', e: '#6fd16b', w: '#d8dae0' },
      shiny: { g: '#2f2f38', w: '#5a5a66', e: '#f2c94c' },
      rows: mirror([
        '........',
        '........',
        '.k......',
        '.kk.....',
        '.kpk....',
        '.kgpkkkk',
        '.kgggggg',
        '.kgggggg',
        '.kgekggg',
        '.kgekggg',
        'wkgggggp',
        '.wkggkgk',
        '.kgggggg',
        '..kggggg',
        '...kkkkk',
        '........',
      ]),
    },
    lion: {
      hint: 'A basic question that many beginners would be afraid to ask',
      text: {
        es: { name: 'León', kind: 'Se atreve con lo básico' },
        en: { name: 'Lion', kind: 'Dares to ask the basics' },
      },
      crownY: 1,
      palette: { k: '#2a1a0c', m: '#a8501a', n: '#d9822b', y: '#f2c14e', t: '#fbe7b5', w: '#ffffff' },
      shiny: { m: '#8a8070', n: '#cfc6b4', y: '#fff6e0', t: '#ffffff' },
      rows: mirror([
        '...k.k..',
        '..kmkmkk',
        '.kmmnmmm',
        'kmnmmmnm',
        'kmmmkkkk',
        '.kmkyyyy',
        'kmnkkyyy',
        '.kmkykyy',
        'kmmkyyyy',
        '.knkyykk',
        'kmmkyttk',
        '.kmkytwk',
        'kmnmkyyy',
        '.kmmmkkk',
        '..kmnmmm',
        '...kk.kk',
      ]),
    },
    bear: {
      hint: 'Hypothetical: "what if…", imagines a scenario or the future',
      text: {
        es: { name: 'Oso', kind: '¿Y si…?' },
        en: { name: 'Bear', kind: 'What if…?' },
      },
      crownY: 2,
      palette: { k: '#1f140c', b: '#6b4426', d: '#4a2e18', t: '#d9b48a' },
      shiny: { b: '#f1f3f6', d: '#c9d2dc', t: '#ffffff' },
      rows: mirror([
        '........',
        '........',
        '.kkk....',
        'kdbdk...',
        'kddkkkkk',
        '.kbbbbbb',
        'kbbbbbbb',
        'kbbkbbbb',
        'kbbbbbbb',
        'kbbbtttt',
        'kbbtttkk',
        'kbbttttk',
        '.kbbtttt',
        '..kbbbbb',
        '...kkkkk',
        '........',
      ]),
    },
  },
};
