// Space: a retro arcade fleet. Same format as animals.mjs: 16×16 pixel art as text,
// drawn as the left half and mirrored. '.' is transparent; other characters are palette keys.
import { mirror } from '../render.mjs';

export default {
  name: 'Space',
  badges: {
    rocket: {
      hint: 'Asks HOW to do something concrete, step by step',
      text: {
        es: { name: 'Cohete', kind: 'Pregunta el cómo' },
        en: { name: 'Rocket', kind: 'Asks how' },
      },
      crownY: 1,
      palette: { k: '#1b1730', r: '#e04848', w: '#eef0f6', g: '#a9b0c2', b: '#5ec8f2', o: '#f28a2e', y: '#ffd84a' },
      shiny: { r: '#8a5cf0', w: '#ffe9a8', g: '#d9b45a' },
      rows: mirror([
        '........',
        '.......k',
        '......kr',
        '.....krr',
        '.....kww',
        '....kwww',
        '....kwkk',
        '....kgkb',
        '....kgkb',
        '....kwkk',
        '...kkwww',
        '..krkgww',
        '.krrkggg',
        '.kkkkkkk',
        '......oy',
        '.......o',
      ]),
    },
    alien: {
      hint: 'Curious tangent: related, but off the main path',
      text: {
        es: { name: 'Alien', kind: 'Curiosidad lateral' },
        en: { name: 'Alien', kind: 'Curious tangent' },
      },
      crownY: 3,
      palette: { k: '#14240f', g: '#6fd64b', d: '#3f9a2c', w: '#ffffff', y: '#f2e14c' },
      shiny: { g: '#e58ad6', d: '#a8509a' },
      rows: mirror([
        '........',
        '..y.....',
        '...k....',
        '...kkkkk',
        '..kggggg',
        '.kgggggg',
        '.kggkkgg',
        '.kgkkkkg',
        '.kgkwkkg',
        '.kggkkgg',
        '..kggggg',
        '..kdgggk',
        '...kdggg',
        '....kddd',
        '.....kkk',
        '........',
      ]),
    },
    planet: {
      hint: 'Connects the topic to their own job, company or a real case',
      text: {
        es: { name: 'Planeta', kind: 'Lo conecta con su trabajo' },
        en: { name: 'Planet', kind: 'Connects it to their work' },
      },
      crownY: 2,
      palette: { k: '#221530', p: '#4f8ef0', l: '#a8d4ff', d: '#2f5cb8', y: '#f2c14e' },
      shiny: { p: '#e8743c', l: '#ffc89a', d: '#a8401f' },
      rows: mirror([
        '........',
        '........',
        '.....kkk',
        '...kkppp',
        '..kplppp',
        '..kllppp',
        'kkkppppp',
        'kyykkkkk',
        'kyyyyyyy',
        '.kkkkkkk',
        '..kdpppp',
        '..kddppp',
        '...kkddd',
        '.....kkk',
        '........',
        '........',
      ]),
    },
    robot: {
      hint: 'Skeptical: challenges a claim, asks about limits, risks or errors',
      text: {
        es: { name: 'Robot', kind: 'Pregunta escéptica' },
        en: { name: 'Robot', kind: 'Skeptical question' },
      },
      crownY: 3,
      palette: { k: '#1a1d26', m: '#a9b4c6', d: '#6c7890', c: '#ff4a4a', r: '#ff4a4a' },
      shiny: { m: '#e8c35a', d: '#a8812a', c: '#4af2e0' },
      rows: mirror([
        '........',
        '.......r',
        '.......k',
        '..kkkkkk',
        '..kmmmmm',
        '..kmkkkm',
        '.kkmkcck',
        '.kkmkkkm',
        '..kmmmmm',
        '..kmkdkd',
        '..kmmmmm',
        '..kkkkkk',
        '...kdmmm',
        '..kddmmm',
        '..kkkkkk',
        '........',
      ]),
    },
    star: {
      hint: 'Asks WHY something works; wants the underlying concept',
      text: {
        es: { name: 'Estrella', kind: 'Pregunta el porqué' },
        en: { name: 'Star', kind: 'Asks why' },
      },
      crownY: 1,
      palette: { k: '#2a1a0c', y: '#ffd84a', l: '#fff6c2', o: '#f2a02e' },
      shiny: { y: '#7ee8ff', l: '#e8fbff', o: '#3fa0d8' },
      rows: mirror([
        '........',
        '.......k',
        '......ky',
        '......kl',
        '.....kyl',
        'kkkkkkyy',
        '.kyyyyyy',
        '..kyyyyy',
        '...kykyy',
        '....kyyy',
        '....kyyy',
        '...kyyoo',
        '...kyokk',
        '..kyok..',
        '..kkk...',
        '........',
      ]),
    },
  },
};
